keymap:
  - name: Konsole tab switching with bare arrow keys
    application:
      only: org.kde.konsole
    remap:
      Left: Shift-Left
      Right: Shift-Right
      Shift-Left: Left
      Shift-Right: Right

  - name: Brave tab switching with bare arrow keys
    application:
      only: brave-browser
    remap:
      Left: Ctrl-Shift-Tab
      Right: Ctrl-Tab
      Shift-Left: Left
      Shift-Right: Right
