#!/usr/bin/nft -f

# Drop all inbound by default, allow only established connections and specific services.

destroy table inet filter
table inet filter {
  chain input {
    type filter hook input priority filter
    policy drop

    ct state {established, related} accept comment "allow tracked connections"
    iif lo accept comment "allow from loopback"
    meta l4proto { icmp, icmpv6 } accept comment "allow icmp"
    ip saddr 192.168.1.0/24 tcp dport ssh accept comment "allow sshd from LAN"
    iifname "tailscale0" tcp dport ssh accept comment "allow sshd from Tailscale"
    ip saddr 192.168.1.0/24 tcp dport 631 accept comment "allow cups from LAN"
    ip saddr 192.168.1.0/24 tcp dport 9090 accept comment "allow cockpit from LAN"
    pkttype host limit rate 5/second counter reject with icmpx type admin-prohibited
    counter
  }
  chain forward {
    type filter hook forward priority filter
    policy drop
  }
}
