[WebService]
AllowUnencrypted = true
LoginTitle = cmos System Management
Origins = https://localhost:9090 http://localhost:9090 https://cmos:9090 http://cmos:9090 https://cmos.home.arpa:9090 http://cmos.home.arpa:9090 ws://localhost:9090 wss://localhost:9090

[Session]
IdleTimeout = 240
